services:
  detectron2:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - $HOME/.torch/fvcore_cache:/tmp:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - result:/home/appuser/app/result
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
volumes:
  result:
